<a href="https://colab.research.google.com/github/SteAmarante/python-data-science/blob/main/aula_04/estudo_de_caso_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rede de Sensores Oceânicos 4‑D

1. Cenário

A empresa instalou uma malha de boias inteligentes que medem em quatro dimensões:
- (0 m, 5 m, 10 m → 3 níveis)
- (10 pontos)
- (12 pontos)
- (24 leituras em um dia)

Os engenheiros querem simular essa rede completa e extrair estatísticas , praticando criação e manipulação de (ndarrays 4‑D)

In [174]:
import numpy as np

In [175]:
#Criar tensor de dados
# 1. Criar tensor 4-D: profundidade (3) x latitude (10) x longitude (12) x tempo(24h)

tensor = np.random.randint(low=12, high=31, size=(3, 10, 12, 24)).astype(float)
print(tensor)

[[[[15. 16. 29. ... 26. 24. 26.]
   [30. 27. 26. ... 14. 17. 19.]
   [30. 22. 25. ... 21. 28. 24.]
   ...
   [24. 12. 18. ... 12. 30. 25.]
   [21. 12. 17. ... 25. 26. 27.]
   [16. 25. 29. ... 29. 17. 17.]]

  [[17. 14. 26. ... 13. 30. 23.]
   [13. 23. 12. ... 26. 17. 17.]
   [20. 28. 29. ... 19. 20. 26.]
   ...
   [22. 21. 23. ... 23. 23. 25.]
   [19. 20. 26. ... 23. 13. 27.]
   [12. 17. 20. ... 25. 17. 28.]]

  [[24. 23. 25. ... 25. 26. 17.]
   [27. 25. 13. ... 21. 27. 30.]
   [28. 14. 21. ... 13. 16. 15.]
   ...
   [27. 17. 24. ... 24. 16. 17.]
   [18. 30. 12. ... 12. 24. 20.]
   [23. 26. 26. ... 29. 17. 13.]]

  ...

  [[22. 12. 15. ... 12. 24. 23.]
   [17. 24. 26. ... 19. 27. 23.]
   [24. 27. 13. ... 23. 17. 19.]
   ...
   [25. 19. 16. ... 14. 12. 17.]
   [21. 24. 17. ... 14. 23. 21.]
   [24. 12. 29. ... 18. 23. 20.]]

  [[15. 29. 23. ... 24. 14. 12.]
   [13. 19. 26. ... 13. 14. 30.]
   [27. 19. 30. ... 17. 14. 25.]
   ...
   [20. 27. 28. ... 13. 14. 16.]
   [15. 30. 19. ... 15. 29

In [176]:
#Temperatura de todo o tensor. (Média, mínima e máxima)

t_media = np.mean(tensor)
t_min = np.min(tensor)
t_max = np.max(tensor)

print(f"🌡️ A temperatura média de todo o tensor é de {t_media:.2f}")
print(f"\n🌡️ A temperatura mínima de todo o tensor é de {t_min}")
print(f"\n🌡️ A temperatura máxima de todo o tensor é de {t_max}")

🌡️ A temperatura média de todo o tensor é de 21.03

🌡️ A temperatura mínima de todo o tensor é de 12.0

🌡️ A temperatura máxima de todo o tensor é de 30.0


In [177]:
# Vetor de médias para 0 m, 5 m, 10 m.  (Média por profundidade)
media_prof = tensor.mean(axis=(1,2,3))
print("A média de temperatura nas camadas 0m, 5m  e 10m são: ")
for i in range(3):
  print(f"{media_prof[i]:.2f}")

A média de temperatura nas camadas 0m, 5m  e 10m são: 
21.04
21.00
21.06


In [178]:
#  “Mapa” de pico horário (máximo ao longo do dia) (Criar um tensor com os valores máximos a longo do dia) Mostrar o Shape dele
tensor_pico  = tensor.max(axis=3)
tensor_pico.shape

(3, 10, 12)

In [179]:
# Hot‑spot = leitura ≥ 28 °C. Conte quantos hot‑spots por profundidade.
hot_spot = tensor>=28
hot_spot_prof = hot_spot.sum(axis=(1,2,3))
print(f"Foram encontradas {hot_spot_prof} com leitura ≥ 28 °C.")

Foram encontradas [466 458 508] com leitura ≥ 28 °C.


In [180]:
#  Broadcasting para alarme. Sensor da superfície (profundidade índice 0) ficou fora de calibração
tensor_calibrar = tensor[0]-0.8
print(f'Média antes de calibrar: {tensor[0].mean():.2f} ºC')

print(f'\nMédia depois de calibrar: {tensor_calibrar.mean():.2f} ºC')

Média antes de calibrar: 21.04 ºC

Média depois de calibrar: 20.24 ºC


In [191]:
# Use slicing para remover 1 lat & 1 long nos extremos → resultado 3 × 8 × 10 × 24.

t_n = tensor[ : , 1:-1, 1:-1, : ]
print(t_n.shape)

(3, 8, 10, 24)


In [182]:
# Qual hora do dia tende a ser mais quente na camada de 5 m?”
# Calcule média ao longo de lat/long e encontre índice do argmax em eixo tempo.
# Converta para horário (0‑23 h) e discuta possível explicação.

